[package]
name = "apk-bot"
version = "0.0.1"
authors = ["RustedTerrier"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
serenity = {version = "0.9.0-rc.2"}

